owner: constructions-incongrues # Your GitHub organization or username, where this repository lives
repo: superlarsen-status # The name of this repository

sites:
  - name: Libretime
    url: https://libretime-superlarsen.interzone.network
  - name: Icecast
    url: https://icecast-superlarsen.interzone.network
  - name: Castopod
    url: https://castopod-superlarsen.interzone.network/
  - name: Wordpress
    url: https://wordpress-superlarsen.interzone.network/

assignees:
  - trivoallan

status-website:
  cname: status-superlarsen.interzone.network
  name: Superlarsen
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
